// Generated by gencpp from file traj_utils/drone_die.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_DRONE_DIE_H
#define TRAJ_UTILS_MESSAGE_DRONE_DIE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct drone_die_
{
  typedef drone_die_<ContainerAllocator> Type;

  drone_die_()
    : drone_die(0)  {
    }
  drone_die_(const ContainerAllocator& _alloc)
    : drone_die(0)  {
  (void)_alloc;
    }



   typedef int32_t _drone_die_type;
  _drone_die_type drone_die;





  typedef boost::shared_ptr< ::traj_utils::drone_die_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::drone_die_<ContainerAllocator> const> ConstPtr;

}; // struct drone_die_

typedef ::traj_utils::drone_die_<std::allocator<void> > drone_die;

typedef boost::shared_ptr< ::traj_utils::drone_die > drone_diePtr;
typedef boost::shared_ptr< ::traj_utils::drone_die const> drone_dieConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::drone_die_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::drone_die_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::drone_die_<ContainerAllocator1> & lhs, const ::traj_utils::drone_die_<ContainerAllocator2> & rhs)
{
  return lhs.drone_die == rhs.drone_die;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::drone_die_<ContainerAllocator1> & lhs, const ::traj_utils::drone_die_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::drone_die_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::drone_die_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::drone_die_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::drone_die_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::drone_die_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::drone_die_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::drone_die_<ContainerAllocator> >
{
  static const char* value()
  {
    return "469265ba708544468cfac3f514285ad9";
  }

  static const char* value(const ::traj_utils::drone_die_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x469265ba70854446ULL;
  static const uint64_t static_value2 = 0x8cfac3f514285ad9ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::drone_die_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/drone_die";
  }

  static const char* value(const ::traj_utils::drone_die_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::drone_die_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 drone_die\n"
;
  }

  static const char* value(const ::traj_utils::drone_die_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::drone_die_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_die);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drone_die_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::drone_die_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::drone_die_<ContainerAllocator>& v)
  {
    s << indent << "drone_die: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_die);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_DRONE_DIE_H
