// Generated by gencpp from file traj_utils/FormationId.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_FORMATIONID_H
#define TRAJ_UTILS_MESSAGE_FORMATIONID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct FormationId_
{
  typedef FormationId_<ContainerAllocator> Type;

  FormationId_()
    : drone_formation_id(0)
    , car_formation_id(0)  {
    }
  FormationId_(const ContainerAllocator& _alloc)
    : drone_formation_id(0)
    , car_formation_id(0)  {
  (void)_alloc;
    }



   typedef int16_t _drone_formation_id_type;
  _drone_formation_id_type drone_formation_id;

   typedef int16_t _car_formation_id_type;
  _car_formation_id_type car_formation_id;





  typedef boost::shared_ptr< ::traj_utils::FormationId_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::FormationId_<ContainerAllocator> const> ConstPtr;

}; // struct FormationId_

typedef ::traj_utils::FormationId_<std::allocator<void> > FormationId;

typedef boost::shared_ptr< ::traj_utils::FormationId > FormationIdPtr;
typedef boost::shared_ptr< ::traj_utils::FormationId const> FormationIdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::FormationId_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::FormationId_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::FormationId_<ContainerAllocator1> & lhs, const ::traj_utils::FormationId_<ContainerAllocator2> & rhs)
{
  return lhs.drone_formation_id == rhs.drone_formation_id &&
    lhs.car_formation_id == rhs.car_formation_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::FormationId_<ContainerAllocator1> & lhs, const ::traj_utils::FormationId_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::FormationId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::FormationId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::FormationId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::FormationId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::FormationId_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::FormationId_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::FormationId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b546e1d2050d5e3211b5e5e45523d88e";
  }

  static const char* value(const ::traj_utils::FormationId_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb546e1d2050d5e32ULL;
  static const uint64_t static_value2 = 0x11b5e5e45523d88eULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::FormationId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/FormationId";
  }

  static const char* value(const ::traj_utils::FormationId_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::FormationId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 drone_formation_id\n"
"int16 car_formation_id\n"
;
  }

  static const char* value(const ::traj_utils::FormationId_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::FormationId_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_formation_id);
      stream.next(m.car_formation_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FormationId_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::FormationId_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::FormationId_<ContainerAllocator>& v)
  {
    s << indent << "drone_formation_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drone_formation_id);
    s << indent << "car_formation_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.car_formation_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_FORMATIONID_H
