// Generated by gencpp from file traj_utils/kill_base.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_KILL_BASE_H
#define TRAJ_UTILS_MESSAGE_KILL_BASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct kill_base_
{
  typedef kill_base_<ContainerAllocator> Type;

  kill_base_()
    : drone_id(0)  {
    }
  kill_base_(const ContainerAllocator& _alloc)
    : drone_id(0)  {
  (void)_alloc;
    }



   typedef int8_t _drone_id_type;
  _drone_id_type drone_id;





  typedef boost::shared_ptr< ::traj_utils::kill_base_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::kill_base_<ContainerAllocator> const> ConstPtr;

}; // struct kill_base_

typedef ::traj_utils::kill_base_<std::allocator<void> > kill_base;

typedef boost::shared_ptr< ::traj_utils::kill_base > kill_basePtr;
typedef boost::shared_ptr< ::traj_utils::kill_base const> kill_baseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::kill_base_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::kill_base_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::kill_base_<ContainerAllocator1> & lhs, const ::traj_utils::kill_base_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::kill_base_<ContainerAllocator1> & lhs, const ::traj_utils::kill_base_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::kill_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::kill_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::kill_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::kill_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::kill_base_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::kill_base_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::kill_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cd4b8fbb9ccb430cf5df0ceccf8d731";
  }

  static const char* value(const ::traj_utils::kill_base_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cd4b8fbb9ccb430ULL;
  static const uint64_t static_value2 = 0xcf5df0ceccf8d731ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::kill_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/kill_base";
  }

  static const char* value(const ::traj_utils::kill_base_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::kill_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 drone_id\n"
;
  }

  static const char* value(const ::traj_utils::kill_base_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::kill_base_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kill_base_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::kill_base_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::kill_base_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_KILL_BASE_H
