// Generated by gencpp from file traj_utils/node_only_drone_node.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_NODE_ONLY_DRONE_NODE_H
#define TRAJ_UTILS_MESSAGE_NODE_ONLY_DRONE_NODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct node_only_drone_node_
{
  typedef node_only_drone_node_<ContainerAllocator> Type;

  node_only_drone_node_()
    : drone_id(0)
    , node_already_reastart(0)  {
    }
  node_only_drone_node_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , node_already_reastart(0)  {
  (void)_alloc;
    }



   typedef int8_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int8_t _node_already_reastart_type;
  _node_already_reastart_type node_already_reastart;





  typedef boost::shared_ptr< ::traj_utils::node_only_drone_node_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::node_only_drone_node_<ContainerAllocator> const> ConstPtr;

}; // struct node_only_drone_node_

typedef ::traj_utils::node_only_drone_node_<std::allocator<void> > node_only_drone_node;

typedef boost::shared_ptr< ::traj_utils::node_only_drone_node > node_only_drone_nodePtr;
typedef boost::shared_ptr< ::traj_utils::node_only_drone_node const> node_only_drone_nodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::node_only_drone_node_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::node_only_drone_node_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::node_only_drone_node_<ContainerAllocator1> & lhs, const ::traj_utils::node_only_drone_node_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.node_already_reastart == rhs.node_already_reastart;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::node_only_drone_node_<ContainerAllocator1> & lhs, const ::traj_utils::node_only_drone_node_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::node_only_drone_node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::node_only_drone_node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::node_only_drone_node_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33299fffa442f68d79e075c04bbd062c";
  }

  static const char* value(const ::traj_utils::node_only_drone_node_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33299fffa442f68dULL;
  static const uint64_t static_value2 = 0x79e075c04bbd062cULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/node_only_drone_node";
  }

  static const char* value(const ::traj_utils::node_only_drone_node_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 drone_id\n"
"int8 node_already_reastart\n"
;
  }

  static const char* value(const ::traj_utils::node_only_drone_node_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.node_already_reastart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_only_drone_node_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::node_only_drone_node_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::node_only_drone_node_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "node_already_reastart: ";
    Printer<int8_t>::stream(s, indent + "  ", v.node_already_reastart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_NODE_ONLY_DRONE_NODE_H
