// Generated by gencpp from file traj_utils/to_drone_state.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_TO_DRONE_STATE_H
#define TRAJ_UTILS_MESSAGE_TO_DRONE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct to_drone_state_
{
  typedef to_drone_state_<ContainerAllocator> Type;

  to_drone_state_()
    : drone_id(0)
    , current_node_state(0)
    , debug_info()  {
    }
  to_drone_state_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , current_node_state(0)
    , debug_info(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int8_t _current_node_state_type;
  _current_node_state_type current_node_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _debug_info_type;
  _debug_info_type debug_info;





  typedef boost::shared_ptr< ::traj_utils::to_drone_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::to_drone_state_<ContainerAllocator> const> ConstPtr;

}; // struct to_drone_state_

typedef ::traj_utils::to_drone_state_<std::allocator<void> > to_drone_state;

typedef boost::shared_ptr< ::traj_utils::to_drone_state > to_drone_statePtr;
typedef boost::shared_ptr< ::traj_utils::to_drone_state const> to_drone_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::to_drone_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::to_drone_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::to_drone_state_<ContainerAllocator1> & lhs, const ::traj_utils::to_drone_state_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.current_node_state == rhs.current_node_state &&
    lhs.debug_info == rhs.debug_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::to_drone_state_<ContainerAllocator1> & lhs, const ::traj_utils::to_drone_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::to_drone_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::to_drone_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::to_drone_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::to_drone_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::to_drone_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::to_drone_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::to_drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82065b5642df1c1cef531f1d008cd434";
  }

  static const char* value(const ::traj_utils::to_drone_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82065b5642df1c1cULL;
  static const uint64_t static_value2 = 0xef531f1d008cd434ULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::to_drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/to_drone_state";
  }

  static const char* value(const ::traj_utils::to_drone_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::to_drone_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 drone_id\n"
"# 4: take_off\n"
"# 5: command\n"
"# 6: land\n"
"int8 current_node_state\n"
"string debug_info\n"
;
  }

  static const char* value(const ::traj_utils::to_drone_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::to_drone_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.current_node_state);
      stream.next(m.debug_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct to_drone_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::to_drone_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::to_drone_state_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "current_node_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.current_node_state);
    s << indent << "debug_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.debug_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_TO_DRONE_STATE_H
