// Generated by gencpp from file traj_utils/YawCmd.msg
// DO NOT EDIT!


#ifndef TRAJ_UTILS_MESSAGE_YAWCMD_H
#define TRAJ_UTILS_MESSAGE_YAWCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace traj_utils
{
template <class ContainerAllocator>
struct YawCmd_
{
  typedef YawCmd_<ContainerAllocator> Type;

  YawCmd_()
    : drone_id(0)
    , cmd_id(0)
    , start_time()
    , cur_yaw(0.0)
    , yaw(0.0)
    , pos()  {
      pos.assign(0.0);
  }
  YawCmd_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , cmd_id(0)
    , start_time()
    , cur_yaw(0.0)
    , yaw(0.0)
    , pos()  {
  (void)_alloc;
      pos.assign(0.0);
  }



   typedef int16_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int32_t _cmd_id_type;
  _cmd_id_type cmd_id;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef float _cur_yaw_type;
  _cur_yaw_type cur_yaw;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef boost::array<float, 3>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::traj_utils::YawCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::traj_utils::YawCmd_<ContainerAllocator> const> ConstPtr;

}; // struct YawCmd_

typedef ::traj_utils::YawCmd_<std::allocator<void> > YawCmd;

typedef boost::shared_ptr< ::traj_utils::YawCmd > YawCmdPtr;
typedef boost::shared_ptr< ::traj_utils::YawCmd const> YawCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::traj_utils::YawCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::traj_utils::YawCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::traj_utils::YawCmd_<ContainerAllocator1> & lhs, const ::traj_utils::YawCmd_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.cmd_id == rhs.cmd_id &&
    lhs.start_time == rhs.start_time &&
    lhs.cur_yaw == rhs.cur_yaw &&
    lhs.yaw == rhs.yaw &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::traj_utils::YawCmd_<ContainerAllocator1> & lhs, const ::traj_utils::YawCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace traj_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::traj_utils::YawCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::traj_utils::YawCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::YawCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::traj_utils::YawCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::YawCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::traj_utils::YawCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::traj_utils::YawCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21833ee83e61e3e1afedb50075e5a16b";
  }

  static const char* value(const ::traj_utils::YawCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21833ee83e61e3e1ULL;
  static const uint64_t static_value2 = 0xafedb50075e5a16bULL;
};

template<class ContainerAllocator>
struct DataType< ::traj_utils::YawCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "traj_utils/YawCmd";
  }

  static const char* value(const ::traj_utils::YawCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::traj_utils::YawCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 drone_id\n"
"int32 cmd_id\n"
"time start_time\n"
"float32 cur_yaw\n"
"float32 yaw\n"
"float32[3] pos \n"
;
  }

  static const char* value(const ::traj_utils::YawCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::traj_utils::YawCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.cmd_id);
      stream.next(m.start_time);
      stream.next(m.cur_yaw);
      stream.next(m.yaw);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YawCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::traj_utils::YawCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::traj_utils::YawCmd_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "cmd_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd_id);
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "cur_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.cur_yaw);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJ_UTILS_MESSAGE_YAWCMD_H
