(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RECV-VAL
          RECV
          ID-VAL
          ID
          LOCAL_ID-VAL
          LOCAL_ID
          UNKNOWN_NUM-VAL
          UNKNOWN_NUM
          FRONTIER_NUM-VAL
          FRONTIER_NUM
          CENTER-VAL
          CENTER
          FRONTIER_CELL_NUMS-VAL
          FRONTIER_CELL_NUMS
          CONTAINED_FRONTIER_IDS-VAL
          CONTAINED_FRONTIER_IDS
          IS_UPDATED-VAL
          IS_UPDATED
          NEED_DIVIDE-VAL
          NEED_DIVIDE
          ACTIVE-VAL
          ACTIVE
          IS_PREV_RELEVANT-VAL
          IS_PREV_RELEVANT
          IS_CUR_RELEVANT-VAL
          IS_CUR_RELEVANT
          IS_COVERED-VAL
          IS_COVERED
          RELEVANT_ID-VAL
          RELEVANT_ID
          RELEVANT_MAP-VAL
          RELEVANT_MAP
          MIN-VAL
          MIN
          MAX-VAL
          MAX
          RESOLUTION-VAL
          RESOLUTION
          GRID_SIZE-VAL
          GRID_SIZE
          MULTI_LAYER_HGRID-VAL
          MULTI_LAYER_HGRID
))