(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CELLS-VAL
          CELLS
          FILTERED_CELLS-VAL
          FILTERED_CELLS
          AVERAGE-VAL
          AVERAGE
          NORMAL-VAL
          NORMAL
          ID-VAL
          ID
          KEYPOSE_IDX-VAL
          KEYPOSE_IDX
          VIEWPOINTS_POS-VAL
          VIEWPOINTS_POS
          VIEWPOINTS_YAW-VAL
          VIEWPOINTS_YAW
          VIEWPOINTS_VISIB_NUM-VAL
          VIEWPOINTS_VISIB_NUM
          BOX_MIN_-VAL
          BOX_MIN_
          BOX_MAX_-VAL
          BOX_MAX_
          PATHS-VAL
          PATHS
          COSTS-VAL
          COSTS
          PATH_TO_HOME_3-VAL
          PATH_TO_HOME_3
          PATH_TO_HOME_4-VAL
          PATH_TO_HOME_4
          COST_TO_HOME-VAL
          COST_TO_HOME
          TOPO_BLACKLIST-VAL
          TOPO_BLACKLIST
          FTR_BLACKLIST-VAL
          FTR_BLACKLIST
))