// Generated by gencpp from file quadrotor_msgs/AnonymousBearingMeas.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_ANONYMOUSBEARINGMEAS_H
#define QUADROTOR_MSGS_MESSAGE_ANONYMOUSBEARINGMEAS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct AnonymousBearingMeas_
{
  typedef AnonymousBearingMeas_<ContainerAllocator> Type;

  AnonymousBearingMeas_()
    : id(0)
    , anonymous_bearing()  {
    }
  AnonymousBearingMeas_(const ContainerAllocator& _alloc)
    : id(0)
    , anonymous_bearing(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _anonymous_bearing_type;
  _anonymous_bearing_type anonymous_bearing;





  typedef boost::shared_ptr< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> const> ConstPtr;

}; // struct AnonymousBearingMeas_

typedef ::quadrotor_msgs::AnonymousBearingMeas_<std::allocator<void> > AnonymousBearingMeas;

typedef boost::shared_ptr< ::quadrotor_msgs::AnonymousBearingMeas > AnonymousBearingMeasPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::AnonymousBearingMeas const> AnonymousBearingMeasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.anonymous_bearing == rhs.anonymous_bearing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df646f67fec5bf09f38afc544e61637c";
  }

  static const char* value(const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf646f67fec5bf09ULL;
  static const uint64_t static_value2 = 0xf38afc544e61637cULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/AnonymousBearingMeas";
  }

  static const char* value(const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"geometry_msgs/PointStamped anonymous_bearing\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.anonymous_bearing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnonymousBearingMeas_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::AnonymousBearingMeas_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "anonymous_bearing: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.anonymous_bearing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_ANONYMOUSBEARINGMEAS_H
