// Generated by gencpp from file quadrotor_msgs/DetectOut.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_DETECTOUT_H
#define QUADROTOR_MSGS_MESSAGE_DETECTOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/Point.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct DetectOut_
{
  typedef DetectOut_<ContainerAllocator> Type;

  DetectOut_()
    : header()
    , image()
    , image_camera()
    , classes()
    , global_poses()  {
    }
  DetectOut_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image(_alloc)
    , image_camera(_alloc)
    , classes(_alloc)
    , global_poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_camera_type;
  _image_camera_type image_camera;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _classes_type;
  _classes_type classes;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _global_poses_type;
  _global_poses_type global_poses;





  typedef boost::shared_ptr< ::quadrotor_msgs::DetectOut_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::DetectOut_<ContainerAllocator> const> ConstPtr;

}; // struct DetectOut_

typedef ::quadrotor_msgs::DetectOut_<std::allocator<void> > DetectOut;

typedef boost::shared_ptr< ::quadrotor_msgs::DetectOut > DetectOutPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::DetectOut const> DetectOutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::DetectOut_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::DetectOut_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::DetectOut_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image == rhs.image &&
    lhs.image_camera == rhs.image_camera &&
    lhs.classes == rhs.classes &&
    lhs.global_poses == rhs.global_poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::DetectOut_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::DetectOut_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::DetectOut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::DetectOut_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::DetectOut_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a4bd95d10ac107281ee8b0f00b03c02";
  }

  static const char* value(const ::quadrotor_msgs::DetectOut_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a4bd95d10ac1072ULL;
  static const uint64_t static_value2 = 0x81ee8b0f00b03c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/DetectOut";
  }

  static const char* value(const ::quadrotor_msgs::DetectOut_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"sensor_msgs/Image image\n"
"string image_camera\n"
"int32[] classes\n"
"geometry_msgs/Point[] global_poses\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::DetectOut_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image);
      stream.next(m.image_camera);
      stream.next(m.classes);
      stream.next(m.global_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectOut_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::DetectOut_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::DetectOut_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "image_camera: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_camera);
    s << indent << "classes[]" << std::endl;
    for (size_t i = 0; i < v.classes.size(); ++i)
    {
      s << indent << "  classes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.classes[i]);
    }
    s << indent << "global_poses[]" << std::endl;
    for (size_t i = 0; i < v.global_poses.size(); ++i)
    {
      s << indent << "  global_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.global_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_DETECTOUT_H
