// Generated by gencpp from file quadrotor_msgs/DistanceMeas.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_DISTANCEMEAS_H
#define QUADROTOR_MSGS_MESSAGE_DISTANCEMEAS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <quadrotor_msgs/LinktrackNodeframe3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct DistanceMeas_
{
  typedef DistanceMeas_<ContainerAllocator> Type;

  DistanceMeas_()
    : header()
    , distance_meas()  {
    }
  DistanceMeas_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance_meas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::quadrotor_msgs::LinktrackNodeframe3_<ContainerAllocator>  _distance_meas_type;
  _distance_meas_type distance_meas;





  typedef boost::shared_ptr< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceMeas_

typedef ::quadrotor_msgs::DistanceMeas_<std::allocator<void> > DistanceMeas;

typedef boost::shared_ptr< ::quadrotor_msgs::DistanceMeas > DistanceMeasPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::DistanceMeas const> DistanceMeasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance_meas == rhs.distance_meas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c3b6590cda39f0c3a802590fc69840f";
  }

  static const char* value(const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c3b6590cda39f0cULL;
  static const uint64_t static_value2 = 0x3a802590fc69840fULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/DistanceMeas";
  }

  static const char* value(const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"quadrotor_msgs/LinktrackNodeframe3 distance_meas\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/LinktrackNodeframe3\n"
"uint8 role\n"
"uint8 id\n"
"uint32 local_time\n"
"uint32 system_time\n"
"float32 voltage\n"
"LinktrackNode2[] nodes\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/LinktrackNode2\n"
"uint8 role\n"
"uint8 id\n"
"float32 dis\n"
"float32 fp_rssi\n"
"float32 rx_rssi\n"
;
  }

  static const char* value(const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance_meas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceMeas_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::DistanceMeas_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::DistanceMeas_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_meas: ";
    s << std::endl;
    Printer< ::quadrotor_msgs::LinktrackNodeframe3_<ContainerAllocator> >::stream(s, indent + "  ", v.distance_meas);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_DISTANCEMEAS_H
