// Generated by gencpp from file quadrotor_msgs/Drift.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_DRIFT_H
#define QUADROTOR_MSGS_MESSAGE_DRIFT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Drift_
{
  typedef Drift_<ContainerAllocator> Type;

  Drift_()
    : id(0)
    , drift()  {
    }
  Drift_(const ContainerAllocator& _alloc)
    : id(0)
    , drift(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _drift_type;
  _drift_type drift;





  typedef boost::shared_ptr< ::quadrotor_msgs::Drift_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Drift_<ContainerAllocator> const> ConstPtr;

}; // struct Drift_

typedef ::quadrotor_msgs::Drift_<std::allocator<void> > Drift;

typedef boost::shared_ptr< ::quadrotor_msgs::Drift > DriftPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Drift const> DriftConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::Drift_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::Drift_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::Drift_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Drift_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.drift == rhs.drift;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::Drift_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Drift_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Drift_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Drift_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Drift_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Drift_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Drift_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Drift_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Drift_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e21fca28d0b53387a08170be5838e563";
  }

  static const char* value(const ::quadrotor_msgs::Drift_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe21fca28d0b53387ULL;
  static const uint64_t static_value2 = 0xa08170be5838e563ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Drift_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/Drift";
  }

  static const char* value(const ::quadrotor_msgs::Drift_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Drift_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"geometry_msgs/PoseStamped drift\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::quadrotor_msgs::Drift_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Drift_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.drift);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drift_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Drift_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::Drift_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "drift: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.drift);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_DRIFT_H
