// Generated by gencpp from file quadrotor_msgs/FtrPointArray.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_FTRPOINTARRAY_H
#define QUADROTOR_MSGS_MESSAGE_FTRPOINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct FtrPointArray_
{
  typedef FtrPointArray_<ContainerAllocator> Type;

  FtrPointArray_()
    : PointArray()  {
    }
  FtrPointArray_(const ContainerAllocator& _alloc)
    : PointArray(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _PointArray_type;
  _PointArray_type PointArray;





  typedef boost::shared_ptr< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> const> ConstPtr;

}; // struct FtrPointArray_

typedef ::quadrotor_msgs::FtrPointArray_<std::allocator<void> > FtrPointArray;

typedef boost::shared_ptr< ::quadrotor_msgs::FtrPointArray > FtrPointArrayPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::FtrPointArray const> FtrPointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator2> & rhs)
{
  return lhs.PointArray == rhs.PointArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b72da7cba93373ecc2fd54ff85f47989";
  }

  static const char* value(const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb72da7cba93373ecULL;
  static const uint64_t static_value2 = 0xc2fd54ff85f47989ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/FtrPointArray";
  }

  static const char* value(const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] PointArray\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PointArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FtrPointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::FtrPointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::FtrPointArray_<ContainerAllocator>& v)
  {
    s << indent << "PointArray[]" << std::endl;
    for (size_t i = 0; i < v.PointArray.size(); ++i)
    {
      s << indent << "  PointArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.PointArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_FTRPOINTARRAY_H
