// Generated by gencpp from file quadrotor_msgs/MultiPoseGraph.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_MULTIPOSEGRAPH_H
#define QUADROTOR_MSGS_MESSAGE_MULTIPOSEGRAPH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/UInt16MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct MultiPoseGraph_
{
  typedef MultiPoseGraph_<ContainerAllocator> Type;

  MultiPoseGraph_()
    : header()
    , key_pose_list_xyz()
    , key_pose_list_intensity()
    , pose_edge_p_end()
    , pose_edge_weight()  {
    }
  MultiPoseGraph_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , key_pose_list_xyz(_alloc)
    , key_pose_list_intensity(_alloc)
    , pose_edge_p_end(_alloc)
    , pose_edge_weight(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _key_pose_list_xyz_type;
  _key_pose_list_xyz_type key_pose_list_xyz;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _key_pose_list_intensity_type;
  _key_pose_list_intensity_type key_pose_list_intensity;

   typedef std::vector< ::std_msgs::UInt16MultiArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::UInt16MultiArray_<ContainerAllocator> >::other >  _pose_edge_p_end_type;
  _pose_edge_p_end_type pose_edge_p_end;

   typedef std::vector< ::std_msgs::Float32MultiArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::other >  _pose_edge_weight_type;
  _pose_edge_weight_type pose_edge_weight;





  typedef boost::shared_ptr< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> const> ConstPtr;

}; // struct MultiPoseGraph_

typedef ::quadrotor_msgs::MultiPoseGraph_<std::allocator<void> > MultiPoseGraph;

typedef boost::shared_ptr< ::quadrotor_msgs::MultiPoseGraph > MultiPoseGraphPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::MultiPoseGraph const> MultiPoseGraphConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.key_pose_list_xyz == rhs.key_pose_list_xyz &&
    lhs.key_pose_list_intensity == rhs.key_pose_list_intensity &&
    lhs.pose_edge_p_end == rhs.pose_edge_p_end &&
    lhs.pose_edge_weight == rhs.pose_edge_weight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1253e98cd3689b7af6c77b6941e0ebdc";
  }

  static const char* value(const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1253e98cd3689b7aULL;
  static const uint64_t static_value2 = 0xf6c77b6941e0ebdcULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/MultiPoseGraph";
  }

  static const char* value(const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"#  --- only support single pose graph for now --- #\n"
"geometry_msgs/Point[] key_pose_list_xyz\n"
"float32[] key_pose_list_intensity\n"
"\n"
"# p_start no need to tans, because it is bind with keypoint sequences\n"
"std_msgs/UInt16MultiArray[] pose_edge_p_end\n"
"std_msgs/Float32MultiArray[] pose_edge_weight\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint16[]            data        # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
;
  }

  static const char* value(const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.key_pose_list_xyz);
      stream.next(m.key_pose_list_intensity);
      stream.next(m.pose_edge_p_end);
      stream.next(m.pose_edge_weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiPoseGraph_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::MultiPoseGraph_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "key_pose_list_xyz[]" << std::endl;
    for (size_t i = 0; i < v.key_pose_list_xyz.size(); ++i)
    {
      s << indent << "  key_pose_list_xyz[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.key_pose_list_xyz[i]);
    }
    s << indent << "key_pose_list_intensity[]" << std::endl;
    for (size_t i = 0; i < v.key_pose_list_intensity.size(); ++i)
    {
      s << indent << "  key_pose_list_intensity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.key_pose_list_intensity[i]);
    }
    s << indent << "pose_edge_p_end[]" << std::endl;
    for (size_t i = 0; i < v.pose_edge_p_end.size(); ++i)
    {
      s << indent << "  pose_edge_p_end[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::UInt16MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_edge_p_end[i]);
    }
    s << indent << "pose_edge_weight[]" << std::endl;
    for (size_t i = 0; i < v.pose_edge_weight.size(); ++i)
    {
      s << indent << "  pose_edge_weight[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_edge_weight[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_MULTIPOSEGRAPH_H
