// Generated by gencpp from file quadrotor_msgs/PolyTraj.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_POLYTRAJ_H
#define QUADROTOR_MSGS_MESSAGE_POLYTRAJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct PolyTraj_
{
  typedef PolyTraj_<ContainerAllocator> Type;

  PolyTraj_()
    : drone_id(0)
    , traj_id(0)
    , start_time()
    , hover(false)
    , type(0)
    , yaw(0.0)
    , hover_p()
    , order(0)
    , coef_x()
    , coef_y()
    , coef_z()
    , coef_psi()
    , duration()  {
    }
  PolyTraj_(const ContainerAllocator& _alloc)
    : drone_id(0)
    , traj_id(0)
    , start_time()
    , hover(false)
    , type(0)
    , yaw(0.0)
    , hover_p(_alloc)
    , order(0)
    , coef_x(_alloc)
    , coef_y(_alloc)
    , coef_z(_alloc)
    , coef_psi(_alloc)
    , duration(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int32_t _traj_id_type;
  _traj_id_type traj_id;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef uint8_t _hover_type;
  _hover_type hover;

   typedef uint8_t _type_type;
  _type_type type;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _hover_p_type;
  _hover_p_type hover_p;

   typedef uint8_t _order_type;
  _order_type order;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coef_x_type;
  _coef_x_type coef_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coef_y_type;
  _coef_y_type coef_y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coef_z_type;
  _coef_z_type coef_z;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coef_psi_type;
  _coef_psi_type coef_psi;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> const> ConstPtr;

}; // struct PolyTraj_

typedef ::quadrotor_msgs::PolyTraj_<std::allocator<void> > PolyTraj;

typedef boost::shared_ptr< ::quadrotor_msgs::PolyTraj > PolyTrajPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::PolyTraj const> PolyTrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::PolyTraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::PolyTraj_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::PolyTraj_<ContainerAllocator2> & rhs)
{
  return lhs.drone_id == rhs.drone_id &&
    lhs.traj_id == rhs.traj_id &&
    lhs.start_time == rhs.start_time &&
    lhs.hover == rhs.hover &&
    lhs.type == rhs.type &&
    lhs.yaw == rhs.yaw &&
    lhs.hover_p == rhs.hover_p &&
    lhs.order == rhs.order &&
    lhs.coef_x == rhs.coef_x &&
    lhs.coef_y == rhs.coef_y &&
    lhs.coef_z == rhs.coef_z &&
    lhs.coef_psi == rhs.coef_psi &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::PolyTraj_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::PolyTraj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9854eb9f815a5897109a390ffc0a0ccf";
  }

  static const char* value(const ::quadrotor_msgs::PolyTraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9854eb9f815a5897ULL;
  static const uint64_t static_value2 = 0x109a390ffc0a0ccfULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/PolyTraj";
  }

  static const char* value(const ::quadrotor_msgs::PolyTraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 drone_id\n"
"int32 traj_id\n"
"time start_time\n"
"\n"
"bool hover\n"
"uint8 type\n"
"float32 yaw\n"
"float32[] hover_p\n"
"\n"
"uint8 order\n"
"float32[] coef_x\n"
"float32[] coef_y\n"
"float32[] coef_z\n"
"float32[] coef_psi\n"
"float32[] duration\n"
;
  }

  static const char* value(const ::quadrotor_msgs::PolyTraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_id);
      stream.next(m.traj_id);
      stream.next(m.start_time);
      stream.next(m.hover);
      stream.next(m.type);
      stream.next(m.yaw);
      stream.next(m.hover_p);
      stream.next(m.order);
      stream.next(m.coef_x);
      stream.next(m.coef_y);
      stream.next(m.coef_z);
      stream.next(m.coef_psi);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolyTraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::PolyTraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::PolyTraj_<ContainerAllocator>& v)
  {
    s << indent << "drone_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "traj_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "hover: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hover);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "hover_p[]" << std::endl;
    for (size_t i = 0; i < v.hover_p.size(); ++i)
    {
      s << indent << "  hover_p[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.hover_p[i]);
    }
    s << indent << "order: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.order);
    s << indent << "coef_x[]" << std::endl;
    for (size_t i = 0; i < v.coef_x.size(); ++i)
    {
      s << indent << "  coef_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coef_x[i]);
    }
    s << indent << "coef_y[]" << std::endl;
    for (size_t i = 0; i < v.coef_y.size(); ++i)
    {
      s << indent << "  coef_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coef_y[i]);
    }
    s << indent << "coef_z[]" << std::endl;
    for (size_t i = 0; i < v.coef_z.size(); ++i)
    {
      s << indent << "  coef_z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coef_z[i]);
    }
    s << indent << "coef_psi[]" << std::endl;
    for (size_t i = 0; i < v.coef_psi.size(); ++i)
    {
      s << indent << "  coef_psi[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coef_psi[i]);
    }
    s << indent << "duration[]" << std::endl;
    for (size_t i = 0; i < v.duration.size(); ++i)
    {
      s << indent << "  duration[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.duration[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_POLYTRAJ_H
