cd ~/workspace/VLA_Diff;
conda deactivate
unset ROS_DISTRO
unset ROS_VERSION
unset ROS_PYTHON_VERSION
unset ROS_ROOT
unset ROS_PACKAGE_PATH
unset ROS_MASTER_URI
unset ROS_IP
unset ROS_HOSTNAME
unset CMAKE_PREFIX_PATH
unset LD_LIBRARY_PATH
unset PYTHONPATH
unset AMENT_PREFIX_PATH
unset COLCON_PREFIX_PATH
source /opt/ros/noetic/setup.bash;
source simulation/cv_bridge/devel/setup.bash;
source Openpi/.venv/bin/activate
source ws_bridge/devel/setup.bash;
roslaunch swarm_ros_bridge vla_station.launch;
