drone_0_box_min_x: 0.0
drone_0_box_min_y: -12.0
drone_0_box_min_z: 0.0
drone_0_box_max_x: 15.0
drone_0_box_max_y: 12.0
drone_0_box_max_z: 4.0

drone_1_box_min_x: 10.0
drone_1_box_min_y: -5.0
drone_1_box_min_z: 0.0
drone_1_box_max_x: 35.0
drone_1_box_max_y: 12.0
drone_1_box_max_z: 4.0

drone_2_box_min_x: 12.0
drone_2_box_min_y: -12.0
drone_2_box_min_z: 0.0
drone_2_box_max_x: 35.0
drone_2_box_max_y: -1.0
drone_2_box_max_z: 4.0
